name: Deploy Dev - Vue Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias e gerar build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | base64 --decode > ~/.ssh/id_ed25519 2>/dev/null || echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Enviar build para Hostinger via Rsync
        run: |
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no" \
            frontend/dist/ \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/u288255425/domains/omman.com.br/public_html/dev/

      - name: Enviar build para Hostinger via Rsync
        run: |
          rsync -avz --delete \
            --chmod=D755,F644 \
            -e "ssh -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no" \
            frontend/dist/ \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/u288255425/domains/omman.com.br/public_html/dev/